/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Michael
 */
public class frmRegisSal extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentRegisSal
     */
    public frmRegisSal() {
        initComponents();
    }

    public JButton getBtnRegistrarSal() {
        return btnRegistrarSal;
    }

    public JButton getBtnCrearRecibo() {
        return btnCrearRecibo;
    }

    public JTextField getTxtRegEnt1() {
        return txtRegEnt1;
    }

    public void setTxtRegEnt1(JTextField txtRegEnt1) {
        this.txtRegEnt1 = txtRegEnt1;
    }

    public void setBtnCrearRecibo(JButton btnCrearRecibo) {
        this.btnCrearRecibo = btnCrearRecibo;
    }

    public void setBtnRegistrarSal(JButton btnRegistrarSal) {
        this.btnRegistrarSal = btnRegistrarSal;
    }

    public JComboBox<String> getCmbTipoVehiculoSal() {
        return cmbTipoVehiculoSal;
    }

    public void setCmbTipoVehiculoSal(JComboBox<String> cmbTipoVehiculoSal) {
        this.cmbTipoVehiculoSal = cmbTipoVehiculoSal;
    }

    public JTextField getTxtRegSalida() {
        return txtRegSalida;
    }

    public void setTxtRegSalida(JTextField txtRegSalida) {
        this.txtRegSalida = txtRegSalida;
    }


    public JTextField getTxtPlacaSal() {
        return txtPlacaSal;
    }

    public void setTxtPlacaSal(JTextField txtPlacaSal) {
        this.txtPlacaSal = txtPlacaSal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlacaSal = new javax.swing.JTextField();
        btnRegistrarSal = new javax.swing.JButton();
        cmbTipoVehiculoSal = new javax.swing.JComboBox<>();
        lblTipoVehiculo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        txtRegSalida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCrearRecibo = new javax.swing.JButton();
        lblSalida1 = new javax.swing.JLabel();
        txtRegEnt1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro de Salida");

        txtPlacaSal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnRegistrarSal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarSal.setText("Registrar Salida");

        cmbTipoVehiculoSal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbTipoVehiculoSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));
        cmbTipoVehiculoSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVehiculoSalActionPerformed(evt);
            }
        });

        lblTipoVehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoVehiculo.setText("Tipo Vehiculo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Placa");

        lblSalida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSalida.setText("Hora Salida");

        txtRegSalida.setText("         :         :");

        jLabel1.setText("hh  /  mm /  ss  ");

        btnCrearRecibo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearRecibo.setText("Crear Recibo");

        lblSalida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSalida1.setText("Hora Entrada");

        txtRegEnt1.setText("         :         :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarSal)
                            .addComponent(lblSalida)
                            .addComponent(jLabel2)
                            .addComponent(lblTipoVehiculo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlacaSal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoVehiculoSal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel1))
                                    .addComponent(txtRegSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnCrearRecibo))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalida1)
                        .addGap(35, 35, 35)
                        .addComponent(txtRegEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoVehiculoSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoVehiculo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlacaSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalida1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegEnt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSal)
                    .addComponent(btnCrearRecibo))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoVehiculoSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVehiculoSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVehiculoSalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRecibo;
    private javax.swing.JButton btnRegistrarSal;
    private javax.swing.JComboBox<String> cmbTipoVehiculoSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblSalida1;
    private javax.swing.JLabel lblTipoVehiculo;
    public javax.swing.JTextField txtPlacaSal;
    public javax.swing.JTextField txtRegEnt1;
    private javax.swing.JTextField txtRegSalida;
    // End of variables declaration//GEN-END:variables
}
