/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Michael
 */
public class VentPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentPrincipal
     */
    public VentPrincipal() {
        initComponents();
    }

    public JDesktopPane getJdpEscritorio() {
        return jdpEscritorio;
    }

    public void setJdpEscritorio(JDesktopPane jdpEscritorio) {
        this.jdpEscritorio = jdpEscritorio;
    }

    public JMenuBar getjMenuBar1() {
        return jmbMenuBar;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jmbMenuBar = jMenuBar1;
    }

    public JMenu getOpReg() {
        return opReg;
    }

    public void setOpReg(JMenu opReg) {
        this.opReg = opReg;
    }

    public JMenu getOpVer() {
        return opVer;
    }

    public void setOpVer(JMenu opVer) {
        this.opVer = opVer;
    }

    public JMenuItem getOpmRegVeh() {
        return opmRegVeh;
    }

    public void setOpmRegVeh(JMenuItem opmRegVeh) {
        this.opmRegVeh = opmRegVeh;
    }

    public VentPrincipal(JMenuItem opmRegVeh) {
        this.opmRegVeh = opmRegVeh;
    }

    public JMenuItem getOpmRegEntVeh() {
        return opmRegEntVeh;
    }

    public void setOpmRegEntVeh(JMenuItem opmRegEntVeh) {
        this.opmRegEntVeh = opmRegEntVeh;
    }

    public JMenuItem getOpmRegSalVeh() {
        return opmRegSalVeh;
    }

    public void setOpmRegSalVeh(JMenuItem opmRegSalVeh) {
        this.opmRegSalVeh = opmRegSalVeh;
    }

    public JMenuItem getOpmSalir() {
        return opmSalir;
    }

    public void setOpmSalir(JMenuItem opmSalir) {
        this.opmSalir = opmSalir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jmbMenuBar = new javax.swing.JMenuBar();
        opReg = new javax.swing.JMenu();
        opmRegEntVeh = new javax.swing.JMenuItem();
        opmRegSalVeh = new javax.swing.JMenuItem();
        opmSalir = new javax.swing.JMenuItem();
        opVer = new javax.swing.JMenu();
        opmRegVeh = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        opReg.setText("Registrar");

        opmRegEntVeh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        opmRegEntVeh.setText("Registrar Entrada Vehiculo");
        opReg.add(opmRegEntVeh);

        opmRegSalVeh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        opmRegSalVeh.setText("Registrar Salida Vehiculo");
        opReg.add(opmRegSalVeh);

        opmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        opmSalir.setText("Salir");
        opmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmSalirActionPerformed(evt);
            }
        });
        opReg.add(opmSalir);

        jmbMenuBar.add(opReg);

        opVer.setText("Mostrar");

        opmRegVeh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        opmRegVeh.setText("Registro de Vehiculos");
        opmRegVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmRegVehActionPerformed(evt);
            }
        });
        opVer.add(opmRegVeh);

        jmbMenuBar.add(opVer);

        setJMenuBar(jmbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmSalirActionPerformed

    private void opmRegVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmRegVehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmRegVehActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenuBar jmbMenuBar;
    private javax.swing.JMenu opReg;
    private javax.swing.JMenu opVer;
    private javax.swing.JMenuItem opmRegEntVeh;
    private javax.swing.JMenuItem opmRegSalVeh;
    private javax.swing.JMenuItem opmRegVeh;
    private javax.swing.JMenuItem opmSalir;
    // End of variables declaration//GEN-END:variables
}
